### ISSUE TITLE
p4 failing checksum

### ISSUE THREAD

**Issue by jordigg** [caskater4/chocolatey-packages#2]
The current p4 choco package is failing on checksum.
Also on the install file seems to have been included git conflict markers.

Latest version is 17.01 available at http://filehost.perforce.com/perforce/r17.1/

**Comment by petemounce** [comment]
Fixed by #5 once it gets merged.

**Comment by caskater4** [comment]
Don't believe this applies anymore. Apologies for the long delay in response. Let me know if this happens again.
